// Datos del nivel Barcelona.
// Todas las posiciones en píxeles de diseño (altura de referencia 1080 px).
// GameScene aplica altScale al colocarlas; con la resolución fija de Fase 2 altScale = 1.

export const BARCELONA = {
    anchoNivel: 30000,
    finNivel:   29600, // x donde termina el nivel (puerta del Imserso)

    jugadorInicio: { x: 130, y: 320 },

    // Bloques de suelo y huecos. GameScene los recorre para crear el suelo estático.
    bloquesYHuecos: [
        { x: 0,     ancho: 2800 },
        { hueco: 350 },
        { x: 3150,  ancho: 5000 },
        { hueco: 2000 },
        { x: 10150, ancho: 3050 },
        { hueco: 200 },
        { x: 13400, ancho: 3000 },
        { hueco: 250 },
        { x: 16650, ancho: 5000 },
        { hueco: 250 },
        { x: 21900, ancho: 100 },
        { hueco: 200 },
        { x: 22200, ancho: 80 },
        { hueco: 300 },
        { x: 22580, ancho: 120 },
        { hueco: 250 },
        { x: 22950, ancho: 50 },
        { hueco: 300 },
        { x: 23300, ancho: 100 },
        { hueco: 200 },
        { x: 23600, ancho: 6400 },
    ],

    // Plataformas elevadas. tipo 'uno' = una pieza, 'dos' = dos piezas, 'grande' = pieza ancha.
    plataformas: [
        { tipo: 'uno',    x: 550,   y: 320 },
        { tipo: 'uno',    x: 872,   y: 500 },
        { tipo: 'uno',    x: 1120,  y: 500 },
        { tipo: 'dos',    x1: 1510, y1: 700,  x2: 1607,  y2: 700 },
        { tipo: 'dos',    x1: 1903, y1: 700,  x2: 2000,  y2: 700 },
        { tipo: 'dos',    x1: 2210, y1: 505,  x2: 2307,  y2: 505 },
        { tipo: 'dos',    x1: 8300, y1: 330,  x2: 8397,  y2: 330 }, // Agujero 1
        { tipo: 'dos',    x1: 8700, y1: 560,  x2: 8797,  y2: 560 }, // Agujero 2
        { tipo: 'uno',    x: 9120,  y: 800 },
        { tipo: 'uno',    x: 9120,  y: 350 },
        { tipo: 'uno',    x: 9470,  y: 400 },
        { tipo: 'uno',    x: 9720,  y: 620 },
        { tipo: 'uno',    x: 9780,  y: 280 },
        { tipo: 'uno',    x: 10470, y: 310 },
        { tipo: 'uno',    x: 10630, y: 550 },
        { tipo: 'uno',    x: 10860, y: 550 },
        { tipo: 'dos',    x1: 11150, y1: 550, x2: 11247, y2: 550 },
        { tipo: 'dos',    x1: 11600, y1: 500, x2: 11697, y2: 500 },
        { tipo: 'uno',    x: 13750, y: 320 }, // Sagrada Família
        { tipo: 'grande', x: 14250, y: 550 },
    ],

    // Imágenes decorativas. x e y en píxeles de diseño; y se cuenta desde abajo.
    // depth y flipX son opcionales (por defecto: sin depth extra, sin flip).
    imagenes: [
        // Tiendas y edificios
        { key: 'cartelBarcelona', x: 400,   y: 120, escala: 0.5  },
        { key: 'quiosco1',        x: 1000,  y: 140, escala: 0.7  },
        { key: 'tiendaComic1',    x: 1750,  y: 140, escala: 0.6  },
        { key: 'pescaderia1',     x: 2250,  y: 170, escala: 0.57 },
        { key: 'panaderia1',      x: 2870,  y: 140, escala: 0.7  },
        { key: 'carniceria1',     x: 3430,  y: 170, escala: 0.55 },
        { key: 'badulaque1',      x: 3940,  y: 140, escala: 0.6  },
        { key: 'carpinteria1',    x: 4470,  y: 170, escala: 0.55 },
        { key: 'informatica1',    x: 5000,  y: 140, escala: 0.6  },
        { key: 'colegio1',        x: 5600,  y: 180, escala: 0.7  },
        { key: 'heladeria1',      x: 6100,  y: 120, escala: 0.7  },
        { key: 'floristeria1',    x: 7100,  y: 120, escala: 0.7  },
        { key: 'colmado1',        x: 7600,  y: 170, escala: 0.5  },
        { key: 'cafeteria1',      x: 10750, y: 140, escala: 0.6  },
        { key: 'bar1',            x: 11650, y: 140, escala: 0.6  },
        { key: 'carniceria2',     x: 11200, y: 170, escala: 0.6  },
        { key: 'drogueria1',      x: 12110, y: 170, escala: 0.6  },
        { key: 'pasteleria1',     x: 12600, y: 140, escala: 0.6  },
        { key: 'bloque4',         x: 24100, y: 140, escala: 0.9  },
        { key: 'bloque2',         x: 25580, y: 140, escala: 0.9  },
        { key: 'bloque6',         x: 25300, y: 140, escala: 1.0  },
        { key: 'bloque1',         x: 26500, y: 140, escala: 0.8  },
        { key: 'bloque2',         x: 28000, y: 140, escala: 0.8  },
        { key: 'bloque3',         x: 28780, y: 140, escala: 0.8  },
        { key: 'imserso1',        x: 29600, y: 140, escala: 0.8  },
        // Objetos decorativos de calle
        { key: 'senal2',          x: 2750,  y: 115, escala: 0.65 },
        { key: 'cono1',           x: 7960,  y: 120, escala: 0.6  },
        { key: 'vallas4',         x: 8050,  y: 94,  escala: 0.6,  depth: 1.5 },
        { key: 'semaforo1',       x: 10250, y: 115, escala: 0.6  },
        { key: 'buzon1',          x: 10400, y: 120, escala: 0.7,  flipX: true },
        { key: 'tierra1',         x: 12980, y: 90,  escala: 0.5,  depth: 1.5, flipX: true },
        { key: 'bocaIncendios1',  x: 14400, y: 140, escala: 0.5  },
        { key: 'basura2',         x: 13600, y: 120, escala: 0.5  },
        { key: 'basura2',         x: 16200, y: 120, escala: 0.5,  flipX: true },
        // Zona obras (agujeros ~21100)
        { key: 'senal1',          x: 21300, y: 95,  escala: 0.7,  depth: 1.5 },
        { key: 'carretilla1',     x: 21450, y: 130, escala: 0.5  },
        { key: 'cono3',           x: 21590, y: 120, escala: 0.6  },
        { key: 'vallas3',         x: 21650, y: 130, escala: 0.6  },
        { key: 'vallas3',         x: 23600, y: 130, escala: 0.6,  flipX: true },
        { key: 'senal3',          x: 23700, y: 110, escala: 0.6  },
        { key: 'tierra2',         x: 23755, y: 95,  escala: 0.6,  depth: 1.5 },
        { key: 'cono2',           x: 23830, y: 98,  escala: 0.6,  depth: 1.5 },
    ],

    // Rangos de elementos repetidos (se colocan con un bucle en GameScene).
    pivotes:    [{ inicio: 13450, fin: 16350 }], // Pivotes Sagrada Família
    vallasObra: [{ inicio: 21750, fin: 23500 }], // Vallas zona obras

    enemigos: {
        palomas:   { inicial: 3, intervalo: 4000, max: 12 },
        patinetes: 20,
        cacas:     5,
    },

    recogibles: {
        frascosGalletas: 3,
        pastillas:       3,
        lunasWukong:     [10550],
        // Pesetas en posiciones fijas y alcanzables; y se cuenta desde abajo.
        // Las de suelo se recogen andando; las altas premian subir a las plataformas.
        pesetas: [
            { x: 700,   y: 190 },
            { x: 1558,  y: 780 }, // sobre la plataforma doble alta
            { x: 2500,  y: 190 },
            { x: 4200,  y: 190 },
            { x: 6600,  y: 190 },
            { x: 7700,  y: 190 },
            { x: 9120,  y: 880 }, // plataforma más alta del agujero grande
            { x: 12300, y: 190 },
            { x: 14250, y: 630 }, // plataforma grande de la Sagrada Família
            { x: 15200, y: 190 },
            { x: 17500, y: 190 },
            { x: 19000, y: 190 },
            { x: 20500, y: 190 },
            { x: 22240, y: 190 }, // bloques estrechos de la zona de obras
            { x: 23350, y: 190 },
            { x: 24500, y: 190 },
            { x: 26000, y: 190 },
            { x: 29000, y: 190 },
        ],
    },

    // Manifiesto de assets. CargaScene lo consume para mostrar la barra de progreso.
    assets: {
        imagenes: [
            { key: 'backgroundMountain', ruta: 'assets/backgroundMountain.png' },
            { key: 'backgroundCiudad',   ruta: 'assets/backgroundCiudadCompleto.png' },
            { key: 'cesped',             ruta: 'assets/cesped2.png' },
            { key: 'suelo',              ruta: 'assets/platform.png' },
            { key: 'particulas',         ruta: 'assets/particulas.png' },
            { key: 'plataformasL',       ruta: 'assets/plataformaBcnIzq.png' },
            { key: 'plataformasR',       ruta: 'assets/plataformaBcnDer.png' },
            { key: 'plataformasC',       ruta: 'assets/plataformaBcnCentro.png' },
            { key: 'monumento1',         ruta: 'assets/colon1.png' },
            { key: 'monumento2',         ruta: 'assets/torresMafre1.png' },
            { key: 'monumento3',         ruta: 'assets/sagradaFamilia1.png' },
            { key: 'monumento4',         ruta: 'assets/torreGlorias1.png' },
            { key: 'monumento5',         ruta: 'assets/arcoTriunfo.png' },
            { key: 'monumento6',         ruta: 'assets/pedrera.png' },
            { key: 'nube1',              ruta: 'assets/nube1.png' },
            { key: 'nube2',              ruta: 'assets/nube2.png' },
            { key: 'nube3',              ruta: 'assets/nube3.png' },
            { key: 'indicadorVida',      ruta: 'assets/indicadorVida.png' },
            { key: 'indicadorVida2',     ruta: 'assets/indicadorVida2.png' },
            { key: 'vidaIcono',          ruta: 'assets/vidaIcono.png' },
            { key: 'galleta',            ruta: 'assets/galleta.png' },
            { key: 'frascoGalletas',     ruta: 'assets/frascoGalletas.png' },
            { key: 'soundOn',            ruta: 'assets/soundOn.png' },
            { key: 'soundOff',           ruta: 'assets/soundOff.png' },
            { key: 'cartelBarcelona',    ruta: 'assets/cartelBarcelona.png' },
            { key: 'quiosco1',           ruta: 'assets/edificios/quiosco1.png' },
            { key: 'tiendaComic1',       ruta: 'assets/edificios/tiendaComic1.png' },
            { key: 'panaderia1',         ruta: 'assets/edificios/panaderia1.png' },
            { key: 'pescaderia1',        ruta: 'assets/edificios/pescaderia1.png' },
            { key: 'carniceria1',        ruta: 'assets/edificios/carniceria1.png' },
            { key: 'carpinteria1',       ruta: 'assets/edificios/carpinteria1.png' },
            { key: 'badulaque1',         ruta: 'assets/edificios/badulaque1.png' },
            { key: 'informatica1',       ruta: 'assets/edificios/informatica1.png' },
            { key: 'valla',              ruta: 'assets/valla.png' },
            { key: 'colegio1',           ruta: 'assets/edificios/colegio1.png' },
            { key: 'heladeria1',         ruta: 'assets/edificios/heladeria1.png' },
            { key: 'colmado1',           ruta: 'assets/edificios/colmado1.png' },
            { key: 'floristeria1',       ruta: 'assets/edificios/floristeria2.png' },
            { key: 'cafeteria1',         ruta: 'assets/edificios/cafeteria1.png' },
            { key: 'carniceria2',        ruta: 'assets/edificios/carniceria2.png' },
            { key: 'drogueria1',         ruta: 'assets/edificios/drogueria1.png' },
            { key: 'pasteleria1',        ruta: 'assets/edificios/pasteleria1.png' },
            { key: 'bar1',               ruta: 'assets/edificios/bar1.png' },
            { key: 'bloque1',            ruta: 'assets/edificios/bloque1.png' },
            { key: 'bloque2',            ruta: 'assets/edificios/bloque2.png' },
            { key: 'bloque3',            ruta: 'assets/edificios/bloque3.png' },
            { key: 'bloque4',            ruta: 'assets/edificios/bloque4.png' },
            { key: 'bloque5',            ruta: 'assets/edificios/bloque5.png' },
            { key: 'bloque6',            ruta: 'assets/edificios/bloque6.png' },
            { key: 'imserso1',           ruta: 'assets/edificios/imserso1.png' },
            { key: 'senal1',             ruta: 'assets/senal1.png' },
            { key: 'senal2',             ruta: 'assets/senal2.png' },
            { key: 'senal3',             ruta: 'assets/senal3.png' },
            { key: 'cono1',              ruta: 'assets/cono1.png' },
            { key: 'cono2',              ruta: 'assets/cono2.png' },
            { key: 'cono3',              ruta: 'assets/cono3.png' },
            { key: 'vallas2',            ruta: 'assets/vallas2.png' },
            { key: 'vallas3',            ruta: 'assets/vallas3.png' },
            { key: 'vallas4',            ruta: 'assets/vallas4.png' },
            { key: 'tierra1',            ruta: 'assets/tierra1.png' },
            { key: 'tierra2',            ruta: 'assets/tierra2.png' },
            { key: 'carretilla1',        ruta: 'assets/carretilla1.png' },
            { key: 'pivote2',            ruta: 'assets/pivote2.png' },
            { key: 'basura1',            ruta: 'assets/basura1.png' },
            { key: 'basura2',            ruta: 'assets/basura2.png' },
            { key: 'buzon1',             ruta: 'assets/buzon1.png' },
            { key: 'bocaIncendios1',     ruta: 'assets/bocaIncendios1.png' },
            { key: 'semaforo1',          ruta: 'assets/semaforo1.png' },
        ],
        spritesheets: [
            { key: 'abuelaMovimiento1',  ruta: 'assets/abuelaAndar.png',             fw: 363,   fh: 378 },
            { key: 'abuelaMovimiento2',  ruta: 'assets/abuelaSalto.png',             fw: 363,   fh: 374 },
            { key: 'abuelaQuieta',       ruta: 'assets/abuelaIdle.png',              fw: 363,   fh: 378 },
            { key: 'abuelaMuerte',       ruta: 'assets/abuelaMuerte.png',            fw: 363,   fh: 378 },
            { key: 'abuelaTWukong',      ruta: 'assets/abuelaTWukong.png',           fw: 452,   fh: 610 },
            { key: 'abuelaMov1Wukong',   ruta: 'assets/abuelaAndarWukongPrueba.png', fw: 362,   fh: 470 },
            { key: 'abuelaQuietaWukong', ruta: 'assets/abuelaIdleWukong.png',        fw: 450,   fh: 470 },
            { key: 'abuelaMov2Wukong',   ruta: 'assets/abuelaSaltoWukong.png',       fw: 450,   fh: 470 },
            { key: 'paracetamol',        ruta: 'assets/paracetamol.png',             fw: 275,   fh: 260 },
            { key: 'lunaWukong',         ruta: 'assets/lunaWukong.png',              fw: 210,   fh: 195 },
            { key: 'paloma',             ruta: 'assets/paloma1.png',                 fw: 370,   fh: 450 },
            { key: 'explosion',          ruta: 'assets/explosion.png',               fw: 298,   fh: 300 },
            { key: 'patinete',           ruta: 'assets/patinete.png',               fw: 313,   fh: 360 },
            { key: 'caca',               ruta: 'assets/caca.png',                   fw: 345,   fh: 300 },
        ],
        audios: [
            { key: 'backgroundSound',    ruta: 'assets/sonidos/pruebaBackground.mp3' },
            { key: 'abuelaSalto',        ruta: 'assets/sonidos/abuelaSalto.mp3' },
            { key: 'cacaSalto',          ruta: 'assets/sonidos/cacaSalto.mp3' },
            { key: 'colisionCacaAsco',   ruta: 'assets/sonidos/colisionCacaAsco.mp3' },
            { key: 'abuelaGolpe',        ruta: 'assets/sonidos/abuelaGolpe.mp3' },
            { key: 'choquePatinete',     ruta: 'assets/sonidos/lauraPatinete2.mp3' },
            { key: 'cogerGalletas',      ruta: 'assets/sonidos/cogerGalletas.mp3' },
            { key: 'lanzarGalleta',      ruta: 'assets/sonidos/lanzarGalleta.wav' },
            { key: 'gritoPatinete',      ruta: 'assets/sonidos/gritoPatinete.wav' },
            { key: 'gritoPajaro1',       ruta: 'assets/sonidos/gritoPajaro1.wav' },
            { key: 'gritoPajaro2',       ruta: 'assets/sonidos/gritoPajaro2.wav' },
            { key: 'gritoTransformacion',ruta: 'assets/sonidos/scream2.mp3' },
        ],
    },
};
